modLoader="javafml"
loaderVersion="[45,)"
license="Academic Free License v3.0"

[[mods]]
modId="thepreend_by_whitewolf"
version="1.0.0"
displayName="The Pre-End"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="WhiteWolf"
description="New dimension means, new blocks and more to explore!"

[[dependencies.thepreend_by_whitewolf]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




